---
title: "Week 7: ARIMA models"
---

```{r}
week <- 7
source(here::here("course_info.R"))
```

## What you will learn this week

* Stationarity and differencing
* Random Walk Models


## Pre-seminar activities

Read [Sections 9.1-9.2 of the textbook](https://otexts.com/fpp3/arima.html) and watch all embedded videos.


## Tutorial exercises

-   Complete Exercise 2-5 from [Section 9.11 of the book](https://otexts.com/fpp3/arima-exercises.html)
-   [Tutorial learning objectives](tute-lo.qmd).
<!-- -   <i class="bi bi-download"></i> [Week 7 Tutorial Solution.html](Week7.html){download="Week 7 Tutorial Solution.html"} -->




<!-- ```{r} -->
<!-- #| output: asis -->
<!-- show_slides(week) -->
<!-- ``` -->

<!-- ## Lectorial activities -->

<!-- ```{r} -->
<!-- #| child: activities.md -->
<!-- ``` -->


<!-- ## Seminar code -->

<!-- ::: {.callout appearance="minimal"} -->
<!-- <i class="bi bi-download"></i> [week7.R](week7.R){download="week7.R"} -->
<!-- ::: -->



```{r, echo=FALSE}
#| output: asis
show_assignments(week)
```
