project:
  type: website
  output-dir: _site
  render:
  - "*.qmd"
  - "!/slides"
  - "!/handouts"
  - "activities.qmd"
  - "!/assignment_data"

website:
  title: "ETF3231/ETF5231 Business Forecasting"
  site-url: "https://adhni.github.io/bf/"
  navbar:
    background: "#006dae"
    left:
      - href: index.qmd
        text: Home
        icon: house-fill
      - text: Weekly schedule
        icon: calendar2-week-fill
        menu:
          - week1/index.qmd
          - week2/index.qmd
          - week3/index.qmd
          - week4/index.qmd
          - week5/index.qmd
          - week6/index.qmd
          - week7/index.qmd
          - week8/index.qmd
          - week9/index.qmd
          - week10/index.qmd
          - week11/index.qmd
          - week12/index.qmd
      - text: Assessments
        icon: clipboard-check-fill
        menu:
          - assignments/A1.qmd
          - assignments/A2.qmd
          - assignments/A3.qmd
          - assignments/A4.qmd
          - assignments/G1.qmd
          - assignments/G2.qmd
          - assignments/G3.qmd
          - assignments/G4.qmd
      - text: Discussion
        icon: chat-fill
        href: https://edstem.org/au/courses/30990
      - text: Moodle
        icon: mortarboard-fill
        href: https://learning.monash.edu/course/view.php?id=26702
      - text: Recordings
        icon: camera-video-fill
        href: https://echo360.net.au/section/630d3bbb-85b4-47c8-842d-4bafc932413d/home
      - text: Textbook
        icon: book
        href: https://OTexts.com/fpp3
    right:
      - icon: github
        href: https://github.com/adhni/bf

date-format: "D MMMM YYYY"

freeze: auto

format:
  html:
    theme: cosmo
    css: numbat.css
    highlight: textmate
    toc: false
    mainfont: "Fira Sans"
    html-math-method: katex
    link-external-newwindow: true
    include-in-header:
      file: header.html

execute:
  echo: false
  message: false
  warning: false
  cache: false
