---
title: "Week 12: Review"
---

```{r}
week <- 12
source(here::here("course_info.R"))
```

```{r}
#| output: asis
show_week_overview(week)
```

<!-- ## What you will learn this week -->

<!-- * Review Assignment 1 -->
<!-- * Announce winner of the forecasting competition -->
<!-- * Discuss exam -->

<!-- ## Pre-seminar activities -->

<!-- Catch up on any exercises not yet done -->


<!-- ## Tutorial exercises -->

<!-- -   [Tutorial learning objectives](tute-lo.qmd). -->
<!-- -   <i class="bi bi-download"></i> [Week 12 Tutorial Solution.html](Tutorial12Solution.html){download="Week 12 Tutorial Solution.html"} -->



<!-- # ```{r} -->
<!-- # #| output: asis -->
<!-- # show_slides(week) -->
<!-- # ``` -->


<!-- ## Post-class activities -->

<!-- * Do any exercises not yet finished. -->
<!-- * Complete past exams: [[2023](exams/Exam2023.pdf)] [[2024](exams/Exam2024.pdf)] -->
<!-- <!-- * Exam solutions: [[2022](exams/Exam2022_solutions.pdf)][[2023](exams/Exam2023_solutions.pdf)][[2024](exams/Exam2024_solutions.pdf)] --> 


<!-- * Re-read the textbook -->
<!-- * Listen again to all lectures -->

## Past exams

* [[2023](exams/Exam2023.pdf)] [[2024](exams/Exam2024.pdf)] 


```{r, echo=FALSE}
#| output: asis
show_assignments(week)
```
