---
title: "Week 8: ARIMA models"
---

```{r}
week <- 8
source(here::here("course_info.R"))
```


## What you will learn this week

* AR, MA, ARMA and ARIMA models
* Selecting model orders manually and automatically

## Pre-seminar activities

Read [Sections 9.3-9.8 of the textbook](https://otexts.com/fpp3/arima.html) and watch all embedded videos


## Tutorial exercises

-   Complete Exercises 7, 8, 15 (a to c), 16 (a to c) from [Section 9.11 of the book](https://otexts.com/fpp3/arima-exercises.html).
-   [Tutorial learning objectives](tute-lo.qmd).
<!-- -   <i class="bi bi-download"></i> [Week 8 Tutorial Solution.html](Week8.html){download="Week 8 Tutorial Solution.html"} -->







<!-- ```{r} -->
<!-- #| output: asis -->
<!-- show_slides(week) -->
<!-- ``` -->

<!-- ## Seminar activities -->

<!-- ```{r} -->
<!-- #| child: activities.md -->
<!-- ``` -->


<!-- ## Seminar code -->

<!-- ::: {.callout appearance="minimal"} -->
<!-- <i class="bi bi-download"></i> [week8.R](week8.R){download="week8.R"} -->
<!-- ::: -->



```{r, echo=FALSE}
#| output: asis
show_assignments(week)
```
