---
title: "Week 5: Exponential smoothing"
---

```{r}
week <- 5
source(here::here("course_info.R"))
```

## What you will learn this week

* Simple exponential smoothing and corresponding ETS models.
* Methods with trend and corresponding ETS models.
* ETS model notation

## Pre-seminar activities

Read [Sections 8.1-8.4 of the textbook](https://otexts.com/fpp3/expsmooth.html) and watch all embedded videos

<!-- # ```{r} -->
<!-- # #| output: asis -->
<!-- # show_slides(week) -->
<!-- # ``` -->

<!-- ## Seminar activities -->

<!-- ```{r} -->
<!-- #| child: activities.md -->
<!-- ``` -->


<!-- ## Seminar code -->

<!-- ::: {.callout appearance="minimal"} -->
<!-- <i class="bi bi-download"></i> [week5.R](week5.R){download="week5.R"} -->
<!-- ::: -->

## Tutorial exercises
-   Complete Exercises 1-5 from [Section 8.8](https://otexts.com/fpp3/expsmooth-exercises.html).
-   [Tutorial learning objectives](tute-lo.qmd).
<!-- -   <i class="bi bi-download"></i> [Week 5 Tutorial Solution.html](Week5.html){download="Week 5 Tutorial Solution.html"} -->



```{r, echo=FALSE}
#| output: asis

show_assignments(week)
```
